# Generated by Django 4.1.6 on 2023-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voices'),
    ]

    operations = [
        migrations.AddField(
            model_name='voices',
            name='audio_title',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
